---  
  - name: Create temporary file for pv
    tempfile:
      state: file
      suffix: temp
    register: tempfile_1
  - template:
      src: pv.j2
      dest: "{{ tempfile_1.path }}"
  - name: Setup pv
    shell: |
      . ./.profile; kubectl apply -f "{{ tempfile_1.path }}"
  - name: Create temporary file for pv
    tempfile:
      state: file
      suffix: temp
    register: tempfile_2
  - template:
      src: helm-config.yaml.j2
      dest: "{{ tempfile_2.path }}"
  - name: Add repo
    shell: |
      . ./.profile; helm repo add gitlab https://charts.gitlab.io/
  - name: Setup lidarr
    shell: ". ./.profile; helm upgrade --install gitlab gitlab/gitlab -f {{ tempfile_2.path }}"