---  
  - name: Create temporary file for pv
    tempfile:
      state: file
      suffix: temp
    register: tempfile_1
  - template:
      src: influxdb-pv.j2
      dest: "{{ tempfile_1.path }}"
  - name: Setup pv
    shell: |
      . ./.profile; kubectl apply -f "{{ tempfile_1.path }}"
  - name: Create temporary file for pv
    tempfile:
      state: file
      suffix: temp
    register: tempfile_2
  - template:
      src: influxdb-helm-config.yaml.j2
      dest: "{{ tempfile_2.path }}"
  - name: Add repo
    shell: |
      . ./.profile; helm repo add bitnami https://charts.bitnami.com/bitnami
  - name: Setup kube-plex
    shell: ". ./.profile; helm upgrade --install influxdb bitnami/influxdb -f {{ tempfile_2.path }}"