---  
  - name: Create temporary file for pv
    tempfile:
      state: file
      suffix: temp
    register: tempfile_1
  - template:
      src: pv.j2
      dest: "{{ tempfile_1.path }}"
  - name: Setup pv
    shell: |
      . ./.profile; kubectl apply -f "{{ tempfile_1.path }}"
  - name: Create temporary file for pv
    tempfile:
      state: file
      suffix: temp
    register: tempfile_2
  - name: Add repo
    shell: |
      . ./.profile; helm repo add k8s-land https://charts.k8s.land
  - template:
      src: helm-config.yaml.j2
      dest: "{{ tempfile_2.path }}"
  - name: Setup kube-plex
    shell: ". ./.profile; helm upgrade --install gitea k8s-land/gitea -f {{ tempfile_2.path }}"