---  
  - name: Create temporary file for pv
    tempfile:
      state: file
      suffix: temp
    register: tempfile_1
  - template:
      src: pv.j2
      dest: "{{ tempfile_1.path }}"
  - name: Setup pv
    shell: |
      . ./.profile; kubectl apply -f "{{ tempfile_1.path }}"
  - name: Create temporary file for pv
    tempfile:
      state: file
      suffix: temp
    register: tempfile_2
  - template:
      src: helm-config.yaml.j2
      dest: "{{ tempfile_2.path }}"
  - git:
      repo: https://github.com/turnrye/ananace-charts.git
      dest: /tmp/ananace-charts
  - name: Setup funkwhale
    shell: ". ./.profile; helm upgrade --install funkwhale /tmp/ananace-charts/charts/funkwhale -f {{ tempfile_2.path }}"