---  
  - name: Create temporary file for pv
    tempfile:
      state: file
      suffix: temp
    register: tempfile_1
  - template:
      src: pv.j2
      dest: "{{ tempfile_1.path }}"
  - name: Setup pv
    shell: |
      . ./.profile; kubectl apply -f "{{ tempfile_1.path }}"
  - git:
      repo: https://github.com/munnerz/kube-plex.git
      dest: /tmp/kube-plex
  - name: Setup kube-plex
    shell: ". ./.profile; helm upgrade --install plex /tmp/kube-plex/charts/kube-plex --set claimToken={{ vault_plex_claim_token }} --set persistence.data.claimName=plex-pvc --set persistence.config.claimName=plex-config-pvc --set persistence.transcode.claimName=plex-transcode-pvc --set timezone='America/Chicago' --set persistence.transcode.enabled=true"
  - name: Create temporary file for metallb
    tempfile:
      state: file
      suffix: temp
    register: tempfile_2
  - template:
      src: lb.j2
      dest: "{{ tempfile_2.path }}"
  - name: Setup metallb
    shell: |
      . ./.profile; kubectl apply -f "{{ tempfile_2.path }}"